### ISSUE TITLE
instance of this image in a docker-compose.yml

### ISSUE THREAD

**Issue by Javiseeker** [Starefossen/docker-transporter#3]
Hi,
I would like to know how to finish this installation in a docker-compose.yml. I'm stuck trying to pass this dockerfile settings: 
```
$ docker run --name my-transport \
  -v "$(pwd):/usr/src/app"
  -d starefossen/transport
```
Is this (pwd) the root of my server? -v stands as Volumes?
Here's my code snippet:

```
  postgres:
    image: postgres
    container_name: "postgres_db"
    env_file:
      - postgres-database.env
    volumes:
      - ./postgres-database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  mongo:
    image: mongo
    container_name: "mongo_db"
    env_file:
      - mongo-database.env
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"
  etl:
    image: starefossen/transporter
    container_name: "etl"
    volumes:

    depends_on:
      - mongo
      - postgres
    links:
      - mongo
      - postgres
```
